### ISSUE TITLE
Chat should update time passed correctly

### ISSUE THREAD

**Issue by luminaxster** [devuxd/SeeCodeRun#186]
![image](https://cloud.githubusercontent.com/assets/6577822/18799844/f8611494-81a7-11e6-8955-6767985c2c45.png)
When a minute passes it shows an hour and it should have been minutes.

**Comment by kenmatsuda** [comment]
I think i have fixed the time

**Comment by luminaxster** [comment]
Awesome! I created a pull request and added some comments.

**Comment by tlatoza** [comment]
This still seems to be broken.

**Comment by tlatoza** [comment]
This  is still broken in the deployed version. We're trying to use seeCode.run for another project. @luminaxster Would it be possible to fix this sometime in the next week or so?

**Comment by luminaxster** [comment]
I added the format used by Facebook messenger:  "14:29", if the post was within the last 24 hours, otherwise "MON AT 14:29". If there is group consecutive messages sent by the same user and messages were in the same minute, the username and time are appears only once for that group.
